### ISSUE TITLE
Submodule qunit failed

### ISSUE THREAD

**Issue by ManginAlexander** [cripi-javascript/dz-4-oop#1]
Как я понял нужно сделать вот что:
C:\Users\painandfear\Documents\GitHub\dz-4-oop [master]> git submodule add git:/
/github.com/jquery/qunit.git

Затем вроде все ок копируется...
Cloning into 'qunit'...
remote: Counting objects: 2300, done.
remote: Compressing objects: 100% (1339/1339), done.

Но не все хорошо...
ffatal: read error: Invalid argument84.00 KiB | 18 KiB/s
atal: early EOF
fatal: index-pack failed
Clone of 'git://github.com/jquery/qunit.git' into submodule path 'qunit' failed

Интернет мне ничем не смог помочь

**Comment by azproduction** [comment]
```
git submodule add git://github.com/jquery/qunit.git qunit
Cloning into 'qunit'...
remote: Counting objects: 2300, done.
remote: Compressing objects: 100% (1339/1339), done.
remote: Total 2300 (delta 1187), reused 2038 (delta 955)
Receiving objects: 100% (2300/2300), 374.80 KiB | 125 KiB/s, done.
Resolving deltas: 100% (1187/1187), done.
```

Если не получится просто создай файл `.gitmodules`

```
[submodule "qunit"]
    path = qunit
    url = git://github.com/jquery/qunit.git
```

а потом `git submodule init && git submodule update`

**Comment by ManginAlexander** [comment]
Уиии 1) способ с 3его раза наконец-то преодолел 14% и клонировал репозитории jquery

А второй способ вообще ничего не делал
