### ISSUE TITLE
JSLint негодует

### ISSUE THREAD

**Issue by ManginAlexander** [cripi-javascript/dz-4-oop#5]
var Model = function (data) {
    "use strict";
    var nameField;
    for (nameField in data) {
        this[nameField] = data[nameField];
    }
};

The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.

**Comment by azproduction** [comment]
https://speakerdeck.com/azproduction/kripi-javascript-tsikly-i-funktsii?slide=12
Еще обрати внимание на все слады этого раздела.
